"""Notification CRUD + real-time delivery endpoints.

Endpoints (all under ``/notifications``):
    GET    /                 - list a student's notifications (paginated)
    GET    /unread           - list a student's unread notifications
    POST   /                 - create a notification, push it over the websocket
    PATCH  /{id}/read        - mark one notification read
    PATCH  /read-all         - mark every one of a student's notifications read
    DELETE /{id}             - delete a notification
    WS     /ws/{student_id}  - live feed a connected client receives pushes on

Persistence is SQLite via ``database.SQLiteNotificationRepository``; no
router-owned business logic lives outside this file.
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, Depends, HTTPException, Query, WebSocket, WebSocketDisconnect, status
from pydantic import BaseModel, Field

from database import NotificationRecord, SQLiteNotificationRepository
from services.groq_service import Urgency
from services.scheduler_service import configure as configure_scheduler

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/notifications", tags=["notifications"])


class NotificationOut(BaseModel):
    """API representation of a notification."""

    id: str
    student_id: str
    opportunity_id: str | None
    subject: str
    body: str
    urgency: Urgency
    is_read: bool
    created_at: str
    read_at: str | None

    @classmethod
    def from_record(cls, record: NotificationRecord) -> "NotificationOut":
        """Build the API shape from a stored :class:`NotificationRecord`."""
        return cls(
            id=record.id,
            student_id=record.student_id,
            opportunity_id=record.opportunity_id,
            subject=record.subject,
            body=record.body,
            urgency=record.urgency,
            is_read=record.is_read,
            created_at=record.created_at.isoformat(),
            read_at=record.read_at.isoformat() if record.read_at else None,
        )


class CreateNotificationRequest(BaseModel):
    """Payload to create a notification directly via the API."""

    student_id: str = Field(min_length=1)
    subject: str = Field(min_length=1)
    body: str = Field(min_length=1)
    opportunity_id: str | None = None
    urgency: Urgency = Urgency.MEDIUM


class MarkAllReadResponse(BaseModel):
    """Result of a bulk mark-all-read operation."""

    updated: int = Field(description="Number of notifications marked read.")


class ConnectionManager:
    """Tracks live websocket connections and fans out pushes per student.

    Satisfies ``services.scheduler_service.WebSocketPublisher`` (via
    :meth:`push`), so it doubles as the transport ``send_reminder`` pushes
    through once wired in with ``configure_scheduler`` below.
    """

    def __init__(self) -> None:
        self._connections: dict[str, list[WebSocket]] = {}

    async def connect(self, student_id: str, websocket: WebSocket) -> None:
        """Accept and register a client's websocket for ``student_id``."""
        await websocket.accept()
        self._connections.setdefault(student_id, []).append(websocket)

    def disconnect(self, student_id: str, websocket: WebSocket) -> None:
        """Deregister a client's websocket."""
        connections = self._connections.get(student_id, [])
        if websocket in connections:
            connections.remove(websocket)
        if not connections:
            self._connections.pop(student_id, None)

    async def push(self, student_id: str, payload: dict) -> None:
        """Send ``payload`` as JSON to every connection open for ``student_id``."""
        for websocket in list(self._connections.get(student_id, [])):
            try:
                await websocket.send_json(payload)
            except Exception:
                logger.exception("Failed to push to a websocket for student %s", student_id)
                self.disconnect(student_id, websocket)


# Process-wide singletons. Wired into scheduler_service so reminders
# generated by the scheduler are persisted and pushed through the same
# repository/connection manager the HTTP and websocket endpoints use.
_repository = SQLiteNotificationRepository()
_connection_manager = ConnectionManager()
configure_scheduler(notification_repository=_repository, websocket_publisher=_connection_manager)


def get_repository() -> SQLiteNotificationRepository:
    """FastAPI dependency: the shared notification repository."""
    return _repository


def get_connection_manager() -> ConnectionManager:
    """FastAPI dependency: the shared websocket connection manager."""
    return _connection_manager


@router.get("", response_model=list[NotificationOut], status_code=status.HTTP_200_OK)
async def list_notifications(
    student_id: str = Query(..., min_length=1),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    repository: SQLiteNotificationRepository = Depends(get_repository),
) -> list[NotificationOut]:
    """List a student's notifications, newest first."""
    records = await repository.list_for_student(student_id, limit=limit, offset=offset)
    return [NotificationOut.from_record(r) for r in records]


@router.get("/unread", response_model=list[NotificationOut], status_code=status.HTTP_200_OK)
async def list_unread_notifications(
    student_id: str = Query(..., min_length=1),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    repository: SQLiteNotificationRepository = Depends(get_repository),
) -> list[NotificationOut]:
    """List only a student's unread notifications, newest first."""
    records = await repository.list_for_student(
        student_id, unread_only=True, limit=limit, offset=offset
    )
    return [NotificationOut.from_record(r) for r in records]


@router.post("", response_model=NotificationOut, status_code=status.HTTP_201_CREATED)
async def create_notification(
    payload: CreateNotificationRequest,
    repository: SQLiteNotificationRepository = Depends(get_repository),
    connections: ConnectionManager = Depends(get_connection_manager),
) -> NotificationOut:
    """Create a notification and push it to the student's live connections."""
    record = await repository.create(
        student_id=payload.student_id,
        subject=payload.subject,
        body=payload.body,
        opportunity_id=payload.opportunity_id,
        urgency=payload.urgency,
    )
    out = NotificationOut.from_record(record)
    await connections.push(payload.student_id, {"type": "notification", **out.model_dump()})
    return out


@router.patch("/read-all", response_model=MarkAllReadResponse, status_code=status.HTTP_200_OK)
async def mark_all_read(
    student_id: str = Query(..., min_length=1),
    repository: SQLiteNotificationRepository = Depends(get_repository),
) -> MarkAllReadResponse:
    """Mark every one of a student's unread notifications as read."""
    updated = await repository.mark_all_read(student_id)
    return MarkAllReadResponse(updated=updated)


@router.patch(
    "/{notification_id}/read", response_model=NotificationOut, status_code=status.HTTP_200_OK
)
async def mark_notification_read(
    notification_id: str,
    repository: SQLiteNotificationRepository = Depends(get_repository),
) -> NotificationOut:
    """Mark a single notification as read.

    Raises:
        HTTPException: 404 if no notification with that id exists.
    """
    record = await repository.mark_read(notification_id)
    if record is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Notification '{notification_id}' not found.",
        )
    return NotificationOut.from_record(record)


@router.delete("/{notification_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_notification(
    notification_id: str,
    repository: SQLiteNotificationRepository = Depends(get_repository),
) -> None:
    """Delete a notification.

    Raises:
        HTTPException: 404 if no notification with that id exists.
    """
    deleted = await repository.delete(notification_id)
    if not deleted:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Notification '{notification_id}' not found.",
        )


@router.websocket("/ws/{student_id}")
async def notifications_websocket(
    websocket: WebSocket,
    student_id: str,
    connections: ConnectionManager = Depends(get_connection_manager),
) -> None:
    """Live feed: pushes a JSON payload for every notification created for ``student_id``."""
    await connections.connect(student_id, websocket)
    try:
        while True:
            # This endpoint is push-only; block on receive purely to detect
            # client disconnects (dropping the connection or sending a close frame).
            await websocket.receive_text()
    except WebSocketDisconnect:
        pass
    finally:
        connections.disconnect(student_id, websocket)
